### ISSUE TITLE
Step by Step in the same device?

### ISSUE THREAD

**Issue by DiegoTc** [dominikamann/InfiniSolar-Voltronic-Home-Assistant-Integration#1]
Hi @dominikamann 
Sorry for this question, but new on this area, reading your step by step guide, but all of these steps need to be done in the same device, in my case I'm using a Raspberry Pi. So the MQTT Broker, the MPP -Solar Project and node red, will need to be executed in the same raspberry pi?

**Comment by dominikamann** [comment]
Hi @DiegoTc ,

no, you don't have to install it on the same computer. But it is also not a mistake to do so. Only the MPP-Solar project needs a connection to the inverter ("USB"). The MPP-Solar tool then sends messages to an MQTT broker configured by you (it does not matter where it is installed as long as it is accessible in your network). The node-red flow only transforms the MQTT message, so it does not have to be installed on the same computer.
